/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Device */
        post: operations["register_device_api_v1_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Devices */
        get: operations["my_devices_api_v1_devices_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Device */
        patch: operations["patch_device_api_v1_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/kernels/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kernel Bundle */
        get: operations["kernel_bundle_api_v1_runtime_kernels__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Manifest */
        get: operations["runtime_manifest_api_v1_runtime_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Types */
        get: operations["task_types_api_v1_task_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Task */
        post: operations["validate_task_api_v1_tasks_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/assignments/{assignment_id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fail Assignment */
        post: operations["fail_assignment_api_v1_worker_assignments__assignment_id__fail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/assignments/{assignment_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Result */
        post: operations["submit_result_api_v1_worker_assignments__assignment_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_api_v1_worker_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_v1_worker_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ErrorBody"];
        };
        /** AssignmentPayload */
        AssignmentPayload: {
            /** Assignment Id */
            assignment_id: string;
            /** Chunk Id */
            chunk_id: string;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Input Sha256 */
            input_sha256: string;
            /** Input Url */
            input_url: string;
            /** Kernel */
            kernel: string;
            /** Kernel Version */
            kernel_version: string;
            /** N Features */
            n_features: number;
            /** N Rows */
            n_rows: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Task Id */
            task_id: string;
        };
        /** Benchmark */
        Benchmark: {
            /** Bench Version */
            bench_version: string;
            /** Score Cells Per Sec */
            score_cells_per_sec: number;
        };
        /** Body_upload_dataset_api_v1_datasets_post */
        Body_upload_dataset_api_v1_datasets_post: {
            /** File */
            file: string;
        };
        /** CancelDirective */
        CancelDirective: {
            /** Assignment Id */
            assignment_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cancel";
        };
        /** DatasetOut */
        DatasetOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** DeviceCapabilities */
        DeviceCapabilities: {
            /** Battery */
            battery?: number | null;
            /** Logical Cores */
            logical_cores?: number | null;
            /** Memory Gb Reported */
            memory_gb_reported?: number | null;
            /** Model */
            model?: string | null;
            /** Network Type */
            network_type?: string | null;
            /** Platform Version */
            platform_version?: string | null;
            /** Storage Quota Mb */
            storage_quota_mb?: number | null;
        };
        /** DeviceOut */
        DeviceOut: {
            benchmark?: components["schemas"]["Benchmark"] | null;
            capabilities: components["schemas"]["DeviceCapabilities"];
            device_type: components["schemas"]["DeviceType"];
            /** Id */
            id: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Name */
            name: string;
            runtime?: components["schemas"]["RuntimeInfo"] | null;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Status */
            status: string;
        };
        /** DevicePatch */
        DevicePatch: {
            /** Disabled */
            disabled?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** DeviceRegisterRequest */
        DeviceRegisterRequest: {
            /** @default {} */
            capabilities: components["schemas"]["DeviceCapabilities"];
            /** @default other */
            device_type: components["schemas"]["DeviceType"];
            /** Name */
            name: string;
        };
        /** DeviceRegistered */
        DeviceRegistered: {
            device: components["schemas"]["DeviceOut"];
            /**
             * Device Token
             * @description Shown once; only its hash is stored.
             */
            device_token: string;
        };
        /**
         * DeviceState
         * @enum {string}
         */
        DeviceState: "initializing" | "idle" | "busy";
        /**
         * DeviceType
         * @enum {string}
         */
        DeviceType: "android_phone" | "laptop" | "desktop" | "other";
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Details
             * @default []
             */
            details: unknown[];
            /** Message */
            message: string;
        };
        /** ExecutionSettings */
        ExecutionSettings: {
            /**
             * Max Devices
             * @default 4
             */
            max_devices: number;
            /**
             * Min Devices
             * @default 1
             */
            min_devices: number;
            /** @default wait_for_min_devices */
            start_policy: components["schemas"]["StartPolicy"];
        };
        /** FailRequest */
        FailRequest: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** GaussianNBParams */
        GaussianNBParams: {
            /** Feature Columns */
            feature_columns: string[];
            /** @default drop_rows */
            missing_values: components["schemas"]["MissingValuePolicy"];
            /**
             * Split Seed
             * @default 42
             */
            split_seed: number;
            /** Target Column */
            target_column: string;
            /**
             * Test Fraction
             * @default 0.2
             */
            test_fraction: number;
            /**
             * Var Smoothing
             * @default 1e-9
             */
            var_smoothing: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatRequest */
        HeartbeatRequest: {
            /** Battery */
            battery?: number | null;
            /** Current Assignment Id */
            current_assignment_id?: string | null;
            /** Session Id */
            session_id: string;
            state: components["schemas"]["DeviceState"];
        };
        /** HeartbeatResponse */
        HeartbeatResponse: {
            /**
             * Directives
             * @default []
             */
            directives: (components["schemas"]["RunDirective"] | components["schemas"]["CancelDirective"] | components["schemas"]["RefreshRuntimeDirective"] | components["schemas"]["ReregisterDirective"])[];
            /** Next Heartbeat Ms */
            next_heartbeat_ms: number;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** LinearRidgeParams */
        LinearRidgeParams: {
            /**
             * Alpha
             * @default 1
             */
            alpha: number;
            /** Feature Columns */
            feature_columns: string[];
            /** @default drop_rows */
            missing_values: components["schemas"]["MissingValuePolicy"];
            /**
             * Split Seed
             * @default 42
             */
            split_seed: number;
            /** Target Column */
            target_column: string;
            /**
             * Test Fraction
             * @default 0.2
             */
            test_fraction: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MissingValuePolicy
         * @enum {string}
         */
        MissingValuePolicy: "drop_rows" | "reject";
        /**
         * PartialResultEnvelope
         * @description Worker result: JSON only, never pickle (D9).
         */
        PartialResultEnvelope: {
            /** Input Sha256 */
            input_sha256: string;
            /** Kernel */
            kernel: string;
            /** Kernel Version */
            kernel_version: string;
            /** N Rows */
            n_rows: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Payload Sha256 */
            payload_sha256: string;
            runtime: components["schemas"]["RuntimeInfo"];
            timings: components["schemas"]["ResultTimings"];
        };
        /** RefreshRuntimeDirective */
        RefreshRuntimeDirective: {
            /** Kernel Version */
            kernel_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "refresh_runtime";
        };
        /** ReregisterDirective */
        ReregisterDirective: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reregister";
        };
        /** ResultTimings */
        ResultTimings: {
            /** Compute Ms */
            compute_ms: number;
            /** Download Ms */
            download_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /** RunDirective */
        RunDirective: {
            assignment: components["schemas"]["AssignmentPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run";
        };
        /** RuntimeInfo */
        RuntimeInfo: {
            /** Bundle */
            bundle: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pyodide" | "cpython";
            /** Numpy */
            numpy: string;
            /** Pyodide */
            pyodide?: string | null;
            /** Python */
            python?: string | null;
        };
        /** RuntimeManifest */
        RuntimeManifest: {
            /** Heartbeat Busy Ms */
            heartbeat_busy_ms: number;
            /** Heartbeat Idle Ms */
            heartbeat_idle_ms: number;
            /** Kernel Bundle Sha256 */
            kernel_bundle_sha256: string;
            /** Kernel Bundle Version */
            kernel_bundle_version: string;
            /** Numpy Version */
            numpy_version: string;
            /** Offline After Seconds */
            offline_after_seconds: number;
            /** Pyodide Version */
            pyodide_version: string;
        };
        /** SessionRequest */
        SessionRequest: {
            benchmark: components["schemas"]["Benchmark"];
            /** @default {} */
            capabilities: components["schemas"]["DeviceCapabilities"];
            runtime: components["schemas"]["RuntimeInfo"];
        };
        /** SessionResponse */
        SessionResponse: {
            /** Heartbeat Busy Ms */
            heartbeat_busy_ms: number;
            /** Heartbeat Idle Ms */
            heartbeat_idle_ms: number;
            /** Session Id */
            session_id: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * StartPolicy
         * @enum {string}
         */
        StartPolicy: "wait_for_min_devices";
        /** TaskManifest */
        TaskManifest: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * @default {
             *       "max_devices": 4,
             *       "min_devices": 1,
             *       "start_policy": "wait_for_min_devices"
             *     }
             */
            execution: components["schemas"]["ExecutionSettings"];
            /**
             * Kernel Version
             * @default 1
             * @constant
             */
            kernel_version: "1";
            /** Name */
            name: string;
            /** Params */
            params: components["schemas"]["GaussianNBParams"] | components["schemas"]["LinearRidgeParams"];
            task_type: components["schemas"]["TaskType"];
        };
        /** TaskOut */
        TaskOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Error */
            error?: string | null;
            /** Execution */
            execution: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Kernel Version */
            kernel_version: string;
            /** Name */
            name: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Prepared */
            prepared: {
                [key: string]: unknown;
            };
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Status History */
            status_history: {
                [key: string]: unknown;
            }[];
            /** Task Type */
            task_type: string;
            /** Validation */
            validation: {
                [key: string]: unknown;
            };
            /** Verification Policy */
            verification_policy: {
                [key: string]: unknown;
            };
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "gaussian_nb_train" | "linear_ridge_train";
        /** TaskTypeInfo */
        TaskTypeInfo: {
            /** Description */
            description: string;
            /** Kernel Version */
            kernel_version: string;
            /** Params Schema */
            params_schema: {
                [key: string]: unknown;
            };
            /** Task Type */
            task_type: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Roles */
            roles: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Errors */
            errors: string[];
            /** Ok */
            ok: boolean;
            /**
             * Plan Preview
             * @description Populated from P5 (device-aware planner).
             */
            plan_preview?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_api_v1_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRegistered"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_devices_api_v1_devices_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
        };
    };
    patch_device_api_v1_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    kernel_bundle_api_v1_runtime_kernels__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_manifest_api_v1_runtime_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeManifest"];
                };
            };
        };
    };
    task_types_api_v1_task_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTypeInfo"][];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskManifest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_task_api_v1_tasks_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskManifest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_assignment_api_v1_worker_assignments__assignment_id__fail_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    submit_result_api_v1_worker_assignments__assignment_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartialResultEnvelope"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    heartbeat_api_v1_worker_heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_v1_worker_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
